global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Security.Claims;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Primitives;
global using MDC.Core.Services.Api;
global using MDC.Shared.Models;