// <auto-generated />
using System;
using MDC.Core.Services.Providers.MDCDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDC.Core.Migrations
{
    [DbContext(typeof(MDCDbContext))]
    partial class MDCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbDatacenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Datacenters");
                });

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbVirtualNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tag")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZeroTierNetworkId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("VirtualNetworks");
                });

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DatacenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DatacenterId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbVirtualNetwork", b =>
                {
                    b.HasOne("MDC.Core.Services.Providers.MDCDatabase.DbWorkspace", "Workspace")
                        .WithMany("VirtualNetworks")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbWorkspace", b =>
                {
                    b.HasOne("MDC.Core.Services.Providers.MDCDatabase.DbDatacenter", "Datacenter")
                        .WithMany("Workspaces")
                        .HasForeignKey("DatacenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datacenter");
                });

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbDatacenter", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("MDC.Core.Services.Providers.MDCDatabase.DbWorkspace", b =>
                {
                    b.Navigation("VirtualNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
